// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package jp.co.hzmyh0.roo.searchbookroo.domain;

import java.lang.String;

privileged aspect Bookshelf_Roo_JavaBean {
    
    public String Bookshelf.getName() {
        return this.name;
    }
    
    public void Bookshelf.setName(String name) {
        this.name = name;
    }
    
}
