// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package jp.co.hzmyh0.roo.searchbookroo.domain;

import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import jp.co.hzmyh0.roo.searchbookroo.domain.Bookshelf;
import org.springframework.stereotype.Component;

privileged aspect BookshelfDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BookshelfDataOnDemand: @Component;
    
    private Random BookshelfDataOnDemand.rnd = new SecureRandom();
    
    private List<Bookshelf> BookshelfDataOnDemand.data;
    
    public Bookshelf BookshelfDataOnDemand.getNewTransientBookshelf(int index) {
        Bookshelf obj = new Bookshelf();
        setName(obj, index);
        return obj;
    }
    
    public void BookshelfDataOnDemand.setName(Bookshelf obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Bookshelf BookshelfDataOnDemand.getSpecificBookshelf(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Bookshelf obj = data.get(index);
        return Bookshelf.findBookshelf(obj.getId());
    }
    
    public Bookshelf BookshelfDataOnDemand.getRandomBookshelf() {
        init();
        Bookshelf obj = data.get(rnd.nextInt(data.size()));
        return Bookshelf.findBookshelf(obj.getId());
    }
    
    public boolean BookshelfDataOnDemand.modifyBookshelf(Bookshelf obj) {
        return false;
    }
    
    public void BookshelfDataOnDemand.init() {
        data = Bookshelf.findBookshelfEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Bookshelf' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<jp.co.hzmyh0.roo.searchbookroo.domain.Bookshelf>();
        for (int i = 0; i < 10; i++) {
            Bookshelf obj = getNewTransientBookshelf(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
