// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package jp.co.hzmyh0.roo.searchbookroo.domain;

import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import jp.co.hzmyh0.roo.searchbookroo.domain.Genre;
import org.springframework.stereotype.Component;

privileged aspect GenreDataOnDemand_Roo_DataOnDemand {
    
    declare @type: GenreDataOnDemand: @Component;
    
    private Random GenreDataOnDemand.rnd = new SecureRandom();
    
    private List<Genre> GenreDataOnDemand.data;
    
    public Genre GenreDataOnDemand.getNewTransientGenre(int index) {
        Genre obj = new Genre();
        setName(obj, index);
        return obj;
    }
    
    public void GenreDataOnDemand.setName(Genre obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Genre GenreDataOnDemand.getSpecificGenre(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Genre obj = data.get(index);
        return Genre.findGenre(obj.getId());
    }
    
    public Genre GenreDataOnDemand.getRandomGenre() {
        init();
        Genre obj = data.get(rnd.nextInt(data.size()));
        return Genre.findGenre(obj.getId());
    }
    
    public boolean GenreDataOnDemand.modifyGenre(Genre obj) {
        return false;
    }
    
    public void GenreDataOnDemand.init() {
        data = Genre.findGenreEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Genre' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<jp.co.hzmyh0.roo.searchbookroo.domain.Genre>();
        for (int i = 0; i < 10; i++) {
            Genre obj = getNewTransientGenre(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
