// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package jp.co.hzmyh0.roo.searchbookroo.domain;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ReviewIntegrationTest_Roo_Configurable {
    
    declare @type: ReviewIntegrationTest: @Configurable;
    
}
